spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meal_mover
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test123
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: applearnsql@gmail.com
    password: mskmqsnsomyzficg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
  application:
    name: MealMover
    frontend:
      url: http://localhost:5173
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
#            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/{registrationId}"
            redirect-uri: "http://localhost:8080/api/auth/oauth2/callback/google"
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            user-name-attribute: sub
  profiles:
    active: local
application:
  security:
    jwt:
      secret: iV83M9R8lYnqnHTRrJDSvSzkPxbJwxkWvImXlLDnXCYUoR7K4jnznHuKLDfSrDfB
      tokens:
        access:
          expiration: 86400000  # 24 hours in milliseconds
        activate:
          expiration: 86400000  # 24 hours (adjust as needed)
        reset-password:
          expiration: 3600000   # 1 hour (typically shorter for security)
file:
  upload-dir: ./uploads

