spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/male_mover
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test123
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: applearnsql@gmail.com
    password: mskmqsnsomyzficg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
  application:
    name: MealMover
    frontend:
      url: http://localhost:5173
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
application:
  security:
    jwt:
      secret: iV83M9R8lYnqnHTRrJDSvSzkPxbJwxkWvImXlLDnXCYUoR7K4jnznHuKLDfSrDfB
      tokens:
        access:
          expiration: 86400000  # 24 hours in milliseconds
        registration-client:
          expiration: 86400000  # 24 hours (adjust as needed)
        registration-driver:
          expiration: 86400000  # 24 hours (adjust as needed)
        registration-operator:
          expiration: 86400000  # 24 hours (adjust as needed)
        reset-password:
          expiration: 3600000   # 1 hour (typically shorter for security)
file:
  upload-dir: D:\MealMover\backend\uploads
